language: erlang
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - mkdir -p $TRAVIS_BUILD_DIR/share/love/
  - sudo apt-get install unzip
env:
  matrix:
    - LOVE_VERSION=0.8.0
    - LOVE_VERSION=0.9.0
  global:
    - XDG_DATA_HOME="$TRAVIS_BUILD_DIR/share"
script: make test
